title: Derrik Gratz's personal website
description: My stuff
theme: just-the-docs

url: https://derrik-gratz.github.io/personal-site

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
